/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import Backend.DB.Patient;
import Backend.DB.DBConnector;
import Backend.DB.Consult;
import Backend.DB.SelectedOption;
import Backend.DB.SelectedScreen;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kairav
 */
public class Consults extends javax.swing.JFrame {

    /**
     * Creates new form Consults
     */
    public static int id;
    public static int consults;
    public static int newestconsult;

    public Consults() {
        initComponents();
        ImageIcon pic = new ImageIcon("src\\main\\resources\\pulseNew.png");
        this.setIconImage(pic.getImage());
        setLocationRelativeTo(null);

        //connect to db
        DBConnector.connect();
        id = Integer.parseInt(SelectedOption.downloadSelected());
        fullname.setText(Patient.loadSinglePatient("Firstname", id) + " " + Patient.loadSinglePatient("Surname", id));
        conditionsArea.setText("Conditions: " + Patient.loadSinglePatient("Medical_Conditions", id) + "\nAllergies: " + Patient.loadSinglePatient("Allergy", id));
        newestconsult = Integer.parseInt(Patient.loadSinglePatient("numConsult", id));

        if (newestconsult >= 1) {
            consults = newestconsult;

            illnesses.setText(Consult.nextCon(id, consults, "diagnosis"));
            medication.setText(Consult.nextCon(id, consults, "medication"));
            symptoms.setText(Consult.nextCon(id, consults, "symptom"));
            dateField.setText(Consult.nextCon(id, consults, "date"));
        } else {
            consults = newestconsult + 1;

        }

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DiagnosisButton = new javax.swing.JButton();
        PerscribeButton = new javax.swing.JButton();
        patientName = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        illnessLabel = new javax.swing.JLabel();
        medicationLabel = new javax.swing.JLabel();
        symptomsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medication = new javax.swing.JTextArea();
        illnesses = new javax.swing.JTextField();
        LogconsultButton = new javax.swing.JButton();
        conditionsLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        conditionsArea = new javax.swing.JTextArea();
        dateField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        NextConsultButton = new javax.swing.JButton();
        PreviousConsultButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        symptoms = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoutIcon.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 381, 45, 48));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel1.setText("Consultation");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 0, -1, -1));

        DiagnosisButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        DiagnosisButton.setText("Diagnose Patient");
        DiagnosisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiagnosisButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DiagnosisButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 398, 168, -1));

        PerscribeButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        PerscribeButton.setText("Perscribe Medication");
        PerscribeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerscribeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PerscribeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 399, -1, 29));

        patientName.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        patientName.setText("Patient Name:");
        getContentPane().add(patientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        fullname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 170, 24));

        illnessLabel.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        illnessLabel.setText("Illness:");
        getContentPane().add(illnessLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        medicationLabel.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        medicationLabel.setText("Medication:");
        getContentPane().add(medicationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        symptomsLabel.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        symptomsLabel.setText("Symptoms:");
        getContentPane().add(symptomsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        medication.setColumns(20);
        medication.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        medication.setRows(5);
        jScrollPane1.setViewportView(medication);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 180, 47));

        illnesses.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        getContentPane().add(illnesses, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 180, -1));

        LogconsultButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        LogconsultButton.setText("Log Consult");
        LogconsultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogconsultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LogconsultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 356, 163, -1));

        conditionsLabel.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        conditionsLabel.setText("Conditions and Allergies:");
        getContentPane().add(conditionsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        conditionsArea.setColumns(20);
        conditionsArea.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        conditionsArea.setRows(5);
        jScrollPane2.setViewportView(conditionsArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 180, 59));

        dateField.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        getContentPane().add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 180, -1));

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        dateLabel.setText("Date:");
        getContentPane().add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        NextConsultButton.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        NextConsultButton.setText("Next Consult");
        NextConsultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextConsultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NextConsultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 24, 161, -1));

        PreviousConsultButton.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        PreviousConsultButton.setText("Previous Consult");
        PreviousConsultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousConsultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PreviousConsultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 62, -1, -1));

        symptoms.setColumns(20);
        symptoms.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        symptoms.setRows(5);
        jScrollPane3.setViewportView(symptoms);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 180, 47));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//change screen
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new Patients().setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void DiagnosisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiagnosisButtonActionPerformed
        // TODO add your handling code here:
        SelectedScreen.uploadSelected("diag");
        new SearchScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_DiagnosisButtonActionPerformed

    private void PerscribeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerscribeButtonActionPerformed
        // TODO add your handling code here:
        SelectedScreen.uploadSelected("pers");
        new SearchScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_PerscribeButtonActionPerformed

    //log new consult
    private void LogconsultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogconsultButtonActionPerformed
        // TODO add your handling code here:
        String diagnosis = illnesses.getText();
        String symptom = symptoms.getText();
        String date = dateField.getText();
        String med = medication.getText();
        if (med.isEmpty()==true);
        
        Consult.addCon(id, diagnosis, med, consults, date, symptom, newestconsult);
        newestconsult = consults;


    }//GEN-LAST:event_LogconsultButtonActionPerformed

    //view other consults
    private void NextConsultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextConsultButtonActionPerformed
        // TODO add your handling code here:
        consults++;
        if (consults > newestconsult) {
            consults = newestconsult + 1;
            JOptionPane.showMessageDialog(null, "This is the newest consult.Click Okay to log a new one");
            illnesses.setText("");
            medication.setText("");
            symptoms.setText("");
            dateField.setText("");
            
        } else {

            illnesses.setText(Consult.nextCon(id, consults, "diagnosis"));
            medication.setText(Consult.nextCon(id, consults, "medication"));
            symptoms.setText(Consult.nextCon(id, consults, "symptom"));
            dateField.setText(Consult.nextCon(id, consults, "date"));
        }


    }//GEN-LAST:event_NextConsultButtonActionPerformed

    private void PreviousConsultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousConsultButtonActionPerformed
        // TODO add your handling code here
        consults--;
        if (consults <= 1) {
            consults = 1;
            JOptionPane.showMessageDialog(null, "This is the oldest consult.");
            illnesses.setText(Consult.lastCon(id, consults, "diagnosis"));
            medication.setText(Consult.lastCon(id, consults, "medication"));
            symptoms.setText(Consult.lastCon(id, consults, "symptom"));
            dateField.setText(Consult.lastCon(id, consults, "date"));
            
        } else {
          
        }
    }//GEN-LAST:event_PreviousConsultButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DiagnosisButton;
    private javax.swing.JButton LogconsultButton;
    private javax.swing.JButton NextConsultButton;
    private javax.swing.JButton PerscribeButton;
    private javax.swing.JButton PreviousConsultButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextArea conditionsArea;
    private javax.swing.JLabel conditionsLabel;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel illnessLabel;
    private javax.swing.JTextField illnesses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea medication;
    private javax.swing.JLabel medicationLabel;
    private javax.swing.JLabel patientName;
    private javax.swing.JTextArea symptoms;
    private javax.swing.JLabel symptomsLabel;
    // End of variables declaration//GEN-END:variables
}
