/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import Backend.DB.Patient;
import Backend.DB.DBConnector;
import Backend.DB.Consult;
import Backend.DB.SelectedScreen;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kairav
 */
public class Consults extends javax.swing.JFrame {

    /**
     * Creates new form Consults
     */
    public static int id;
    public static int consults;
    public static int newestconsult;

    public Consults() {
        initComponents();
        ImageIcon pic = new ImageIcon("src\\main\\resources\\pulseNew.png");
        this.setIconImage(pic.getImage());
        setSize(600,440);
        setLocationRelativeTo(null);

        //connect to db
        DBConnector.connect();
        id = Integer.parseInt(SelectedScreen.downloadSelected());
        fullname.setText(Patient.loadSinglePatient("Firstname", id) + " " + Patient.loadSinglePatient("Surname", id));
        conditionsArea.setText("Conditions: " + Patient.loadSinglePatient("Medical_Conditions", id) + "\nAllergies: " + Patient.loadSinglePatient("Allergy", id));
        consults = Integer.parseInt(Patient.loadSinglePatient("numConsult", id));
        newestconsult=consults;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DiagnosisButton = new javax.swing.JButton();
        PerscribeButton = new javax.swing.JButton();
        patientName = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        illnessLabel = new javax.swing.JLabel();
        medicationLabel = new javax.swing.JLabel();
        symptomsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        symptoms = new javax.swing.JTextArea();
        illnesses = new javax.swing.JTextField();
        medication = new javax.swing.JTextField();
        LogconsultButton = new javax.swing.JButton();
        conditionsLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        conditionsArea = new javax.swing.JTextArea();
        dateField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        NextConsultButton1 = new javax.swing.JButton();
        PreviousConsultButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoutIcon.png"))); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel1.setText("Consultation");

        DiagnosisButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        DiagnosisButton.setText("Diagnose Patient");
        DiagnosisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiagnosisButtonActionPerformed(evt);
            }
        });

        PerscribeButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        PerscribeButton.setText("Perscribe Medication");
        PerscribeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerscribeButtonActionPerformed(evt);
            }
        });

        patientName.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        patientName.setText("Patient Name:");

        fullname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        illnessLabel.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        illnessLabel.setText("Illness:");

        medicationLabel.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        medicationLabel.setText("Medication:");

        symptomsLabel.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        symptomsLabel.setText("Symptoms:");

        symptoms.setColumns(20);
        symptoms.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        symptoms.setRows(5);
        jScrollPane1.setViewportView(symptoms);

        illnesses.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        medication.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        LogconsultButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        LogconsultButton.setText("Log Consult");
        LogconsultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogconsultButtonActionPerformed(evt);
            }
        });

        conditionsLabel.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        conditionsLabel.setText("Conditions and Allergies:");

        conditionsArea.setColumns(20);
        conditionsArea.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        conditionsArea.setRows(5);
        jScrollPane2.setViewportView(conditionsArea);

        dateField.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        dateLabel.setText("Date:");

        NextConsultButton1.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        NextConsultButton1.setText("Next Consult");
        NextConsultButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextConsultButton1ActionPerformed(evt);
            }
        });

        PreviousConsultButton.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        PreviousConsultButton.setText("Previous Consult");
        PreviousConsultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousConsultButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(medicationLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(symptomsLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(illnessLabel)))
                            .addComponent(patientName)
                            .addComponent(dateLabel)
                            .addComponent(conditionsLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(medication)
                                            .addComponent(illnesses)
                                            .addComponent(dateField)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PreviousConsultButton)
                                    .addComponent(NextConsultButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DiagnosisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(PerscribeButton)
                                        .addGap(34, 34, 34))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LogconsultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(136, 136, 136)))
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(illnesses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(medication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(patientName)
                                .addGap(10, 10, 10)
                                .addComponent(dateLabel)
                                .addGap(11, 11, 11)
                                .addComponent(illnessLabel)
                                .addGap(11, 11, 11)
                                .addComponent(medicationLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(symptomsLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(NextConsultButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PreviousConsultButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conditionsLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LogconsultButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiagnosisButton)
                            .addComponent(PerscribeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//change screen
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        new Patients().setVisible(true);
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void DiagnosisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiagnosisButtonActionPerformed
        // TODO add your handling code here:
        SelectedScreen.uploadSelected("diag");
        new SearchScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_DiagnosisButtonActionPerformed

    private void PerscribeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerscribeButtonActionPerformed
        // TODO add your handling code here:
        SelectedScreen.uploadSelected("pers");
        new SearchScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_PerscribeButtonActionPerformed

    //log new consult
    private void LogconsultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogconsultButtonActionPerformed
        // TODO add your handling code here:
        consults++;
        String diagnosis = illnesses.getText();
        String symptom = symptoms.getText();
        String date = dateField.getText();
        String med = medication.getText();
        newestconsult = consults;

        Consult.addCon(id, diagnosis, med, consults, date, symptom);

    }//GEN-LAST:event_LogconsultButtonActionPerformed

    //view other consults
    private void NextConsultButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextConsultButton1ActionPerformed
        // TODO add your handling code here:
        if (consults <=newestconsult) {
            consults++;
            illnesses.setText(Consult.nextCon(id, consults, newestconsult, "diagnosis"));
            medication.setText(Consult.nextCon(id, consults, newestconsult, "medication"));
            symptoms.setText(Consult.nextCon(id, consults, newestconsult, "symptom"));
            dateField.setText(Consult.nextCon(id, consults, newestconsult, "date"));

        }else{
            JOptionPane.showMessageDialog(null, "This is the newest consult.Click Okay to log a new one");
            illnesses.setText("");
            medication.setText("");
            symptoms.setText("");
            dateField.setText("");
            
            
        }

    }//GEN-LAST:event_NextConsultButton1ActionPerformed

    private void PreviousConsultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousConsultButtonActionPerformed
        // TODO add your handling code here:
        if (consults > 1) {
            consults--;
            illnesses.setText(Consult.lastCon(id, consults, "diagnosis"));
            medication.setText(Consult.lastCon(id, consults, "medication"));
            symptoms.setText(Consult.lastCon(id, consults, "symptom"));
            dateField.setText(Consult.lastCon(id, consults, "date"));
        } else{
            JOptionPane.showMessageDialog(null, "This is the oldest consult.");
            
        }
    }//GEN-LAST:event_PreviousConsultButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DiagnosisButton;
    private javax.swing.JButton LogconsultButton;
    private javax.swing.JButton NextConsultButton1;
    private javax.swing.JButton PerscribeButton;
    private javax.swing.JButton PreviousConsultButton;
    private javax.swing.JTextArea conditionsArea;
    private javax.swing.JLabel conditionsLabel;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel illnessLabel;
    private javax.swing.JTextField illnesses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField medication;
    private javax.swing.JLabel medicationLabel;
    private javax.swing.JLabel patientName;
    private javax.swing.JTextArea symptoms;
    private javax.swing.JLabel symptomsLabel;
    // End of variables declaration//GEN-END:variables
}
