/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import Backend.Password;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kairav
 */
public class Login extends javax.swing.JFrame {

    
            /**
             * Creates new form Screen1
             */

    public Login() {

        initComponents();

        ImageIcon pic = new ImageIcon("src\\main\\resources\\pulseNew.png");
        this.setIconImage(pic.getImage());
        setLocationRelativeTo(null);
        setSize(600,440);
        incorrectCodeLabel.setVisible(false);
        Screens.setVisible(Password.loggedIn);
        PatientButton.setVisible(Password.loggedIn);
        MedicationButton.setVisible(Password.loggedIn);
        IllnessButton.setVisible(Password.loggedIn);
        logoutButton.setVisible(Password.loggedIn);
        confirmButton.setVisible(!Password.loggedIn);
        if (Password.loggedIn==true) {
            PasswordField.setText(Password.code); 
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        Title = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        confirmButton = new javax.swing.JButton();
        Screens = new javax.swing.JLabel();
        incorrectCodeLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        icon = new javax.swing.JLabel();
        MedicationButton = new javax.swing.JButton();
        instruction = new javax.swing.JLabel();
        PatientButton = new javax.swing.JButton();
        IllnessButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        Title.setText("Doctor Information Terminal");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 13, -1, -1));

        PasswordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 172, -1));

        confirmButton.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 164, -1));

        Screens.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Screens.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Screens.setText("Screens:");
        Screens.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Screens, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 67, 104, -1));

        incorrectCodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        incorrectCodeLabel.setForeground(new java.awt.Color(153, 0, 0));
        incorrectCodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incorrectCodeLabel.setText("Invalid Code");
        incorrectCodeLabel.setToolTipText("");
        incorrectCodeLabel.setInheritsPopupMenu(false);
        incorrectCodeLabel.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(incorrectCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 172, -1));

        exitButton.setBackground(new java.awt.Color(255, 0, 0));
        exitButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 0, 0));
        exitButton.setText("x");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 11, -1, 50));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pulse.png"))); // NOI18N
        icon.setText("jLabel2");
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 265, -1));

        MedicationButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MedicationButton.setText("Medication");
        MedicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MedicationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, -1, -1));

        instruction.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        instruction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instruction.setText("Enter Your Code");
        instruction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(instruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 265, -1));

        PatientButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PatientButton.setText("Patients");
        PatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PatientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 144, 104, -1));

        IllnessButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        IllnessButton.setText("Illness");
        IllnessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IllnessButtonActionPerformed(evt);
            }
        });
        getContentPane().add(IllnessButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 178, 104, -1));

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoutIcon.png"))); // NOI18N
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 372, 45, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Login

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        if (PasswordField.getText() == null) {
            JOptionPane.showMessageDialog(null, "Enter A Code Then Press Confirm");
        } else {
            if (Password.login(PasswordField.getText()) == true) {
                Screens.setVisible(true);
                PatientButton.setVisible(true);
                MedicationButton.setVisible(true);
                IllnessButton.setVisible(true);
                incorrectCodeLabel.setVisible(false);
                logoutButton.setVisible(true);
                confirmButton.setVisible(false);
            } else {
                incorrectCodeLabel.setVisible(true);
                PasswordField.setText("");
            }
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    //Close app
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void PatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientButtonActionPerformed
        // TODO add your handling code here:
        new Patients().setVisible(true);
        dispose();

    }//GEN-LAST:event_PatientButtonActionPerformed

    private void MedicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicationButtonActionPerformed
        // TODO add your handling code here:
        new Medication().setVisible(true);
        dispose();

    }//GEN-LAST:event_MedicationButtonActionPerformed

    private void IllnessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IllnessButtonActionPerformed
        // TODO add your handling code here:
        new Illnesses().setVisible(true);
        dispose();

    }//GEN-LAST:event_IllnessButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        Screens.setVisible(false);
        PatientButton.setVisible(false);
        MedicationButton.setVisible(false);
        IllnessButton.setVisible(false);
        logoutButton.setVisible(true);
        PasswordField.setText("");
        confirmButton.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold> 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IllnessButton;
    private javax.swing.JButton MedicationButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton PatientButton;
    private javax.swing.JLabel Screens;
    private javax.swing.JLabel Title;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel incorrectCodeLabel;
    private javax.swing.JLabel instruction;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
}
