/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import Backend.DB.DBConnector;
import Backend.DB.SelectedOption;
import Backend.DB.Patient;
import Backend.Password;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kairav
 */
public class Patients extends javax.swing.JFrame {

    /**
     * Creates new form Patients
     */
    public Patients() {

        initComponents();
        ImageIcon pic = new ImageIcon("src\\main\\resources\\pulseNew.png");
        this.setIconImage(pic.getImage());
        setLocationRelativeTo(null);

        DBConnector.connect();
        String[] names = Patient.loadPatientList();
        //populates list with patients
        patientList.setListData(names);
    }

    String Criteria = "Firstname";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        listLabel = new javax.swing.JLabel();
        PatientList = new javax.swing.JScrollPane();
        patientList = new javax.swing.JList<>();
        searchField = new javax.swing.JTextField();
        criteriaButton = new javax.swing.JButton();
        instructionLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        newPatientButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(526, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        titleLabel.setText("Doctor Information Terminal");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        editButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 379, -1, -1));

        listLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        listLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listLabel.setText("List Of Patients");
        getContentPane().add(listLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 202, 214, -1));

        patientList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PatientList.setViewportView(patientList);

        getContentPane().add(PatientList, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 239, 300, 101));

        searchField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });
        getContentPane().add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 143, 243, 28));

        criteriaButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        criteriaButton.setText("Change Search Criteria");
        criteriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criteriaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(criteriaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 63, 206, -1));

        instructionLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        instructionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabel.setText("Search Criteria: Firstname");
        getContentPane().add(instructionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 106, 326, -1));

        backButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kairav\\OneDrive\\Pictures\\logoutIcon.png")); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 385, 50, 44));

        newPatientButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        newPatientButton.setText("Add Patient");
        newPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPatientButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newPatientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 379, -1, -1));

        viewButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 379, -1, -1));

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deleteIcon.png"))); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 379, 45, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //update information
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        String selected = patientList.getSelectedValue();
        if (selected == null) {
            JOptionPane.showMessageDialog(null, "Select A Patient first.");
        } else {
            String id = "" + (Patient.getId(selected));
            SelectedOption.uploadSelected(id);
            new PatientUpdate().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_editButtonActionPerformed
//change search criteria
    private void criteriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criteriaButtonActionPerformed
        // TODO add your handling code here:

        Criteria = Patient.criteria(Criteria);
        instructionLabel.setText("Search Criteria: " + Patient.criteriaOut(Criteria));

    }//GEN-LAST:event_criteriaButtonActionPerformed
//change screen
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        Password.loggedIn=true;
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed
    private void newPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPatientButtonActionPerformed
        // TODO add your handling code here
        new PatientAdd().setVisible(true);
        dispose();

    }//GEN-LAST:event_newPatientButtonActionPerformed

//search
    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        // TODO add your handling code here:
        String[] names = Patient.searchPat(searchField.getText(), Criteria);
        patientList.setListData(names);
    }//GEN-LAST:event_searchFieldKeyReleased

    //change screen
    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:

        String selected = patientList.getSelectedValue();
        if (selected == null) {
            JOptionPane.showMessageDialog(null, "Select A Patient first.");
        } else {
            String id = "" + (Patient.getId(selected));
            SelectedOption.uploadSelected(id);
            new Consults().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_viewButtonActionPerformed

    //delete from DB
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:

        String selected = patientList.getSelectedValue();
        if (selected == null) {
            JOptionPane.showMessageDialog(null, "Select A Patient first.");
        } else {
            int id = (Patient.getId(selected));
            Patient.deletePat(selected, id);
            String names[] = Patient.loadPatientList();
            patientList.setListData(names);
        }

    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PatientList;
    private javax.swing.JButton backButton;
    private javax.swing.JButton criteriaButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JLabel listLabel;
    private javax.swing.JButton newPatientButton;
    private javax.swing.JList<String> patientList;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
