/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import Backend.DB.Illness;
import Backend.DB.DBConnector;
import Backend.DB.Medicine;
import Backend.DB.SelectedScreen;
import javax.swing.ImageIcon;

/**
 *
 * @author Kairav
 */
public class SearchScreen extends javax.swing.JFrame {

    /**
     * Creates new form Perscribe
     */
    public SearchScreen() {
        initComponents();
        ImageIcon pic = new ImageIcon("src\\main\\resources\\pulseNew.png");
        this.setIconImage(pic.getImage());
        setSize(600,440);
        setLocationRelativeTo(null);
        DBConnector.connect();
        
        //connect to DB
        if ("diag".equals(SelectedScreen.downloadSelected())) {
            String[] illness = Illness.loadIllnessList();
            List.setListData(illness);
            Title.setText("Diagnose Patient");
            typeLabel.setText("Illness");
            instructions2.setText("Enter The Symptoms:");
            instructions.setText("Separate each sypmtom by a comma");
        } else if ("pers".equals(SelectedScreen.downloadSelected())){
            String[] medication = Medicine.loadMedicationList();
            List.setListData(medication);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        instructions2 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        List = new javax.swing.JList<>();
        typeLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        instructions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        Title.setText("Perscribe Medication");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 0, -1, -1));

        instructions2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        instructions2.setText("Enter The Illness:");
        getContentPane().add(instructions2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        searchField.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });
        getContentPane().add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 106, 136, -1));

        List.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jScrollPane1.setViewportView(List);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 191, 286, -1));

        typeLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        typeLabel.setText("Medication");
        getContentPane().add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 149, -1, -1));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoutIcon.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 377, 43, 43));

        instructions.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        instructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(instructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 580, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //search
    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        // TODO add your handling code here:
        if ("diag".equals(SelectedScreen.downloadSelected())) {
            String[] illness = Illness.searchIll(searchField.getText(), "Symptoms");
            List.setListData(illness);
        } else {
            String[] medication = Medicine.searchMed(searchField.getText(), "illnessTreated");
            List.setListData(medication);
        }

    }//GEN-LAST:event_searchFieldKeyReleased

    //change screen
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new Consults().setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> List;
    private javax.swing.JLabel Title;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel instructions;
    private javax.swing.JLabel instructions2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
